language: go

go:
 - 1.3

before_install:
 - sudo apt-get update -qq
 - export GOPATH=/home/travis/gopath
 - export PATH=$PATH:$GOPATH/bin

install:
 - sudo apt-get install -y libtagc0-dev portaudio1.?9-dev libgpod-dev libvlc-dev

script:
 - make build
 - make test
 - echo help | ./cfmedias
 - echo list | ./cfmedias
 - echo quit | ./cfmedias

 - make
 - echo help | ./cfmedias
 - echo list | ./cfmedias
 - echo quit | ./cfmedias

 - make clean
 - make build
 - echo help | ./cfmedias
 - echo list | ./cfmedias
 - echo quit | ./cfmedias

 - make clean
 - make
 - echo help | ./cfmedias
 - echo list | ./cfmedias
 - echo quit | ./cfmedias
